/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "WebApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "experimentsDb": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "experimentsVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
